Revert "feat: add full build workflow with all sub-tweaks"
This reverts commit b1fc11d37d3af0081486d61ddbaa5ae60430cd14.

diff --git a/.github/workflows/_build_tweaks.yml b/.github/workflows/_build_tweaks.yml
--- a/.github/workflows/_build_tweaks.yml
+++ b/.github/workflows/_build_tweaks.yml
@@ -33,6 +33,16 @@ on:
         required: true
         default: false
 
+      tweak_version:
+        type: string
+        required: false
+        default: ""
+
+      tweak_url:
+        type: string
+        required: false
+        default: ""
+
 jobs:
   build-tweaks:
     name: Build Tweaks
@@ -48,6 +58,7 @@ jobs:
           echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV
 
       - name: Cache Theos
+        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc }}
         id: theos
         uses: actions/cache@v5
         env:
@@ -58,7 +69,7 @@ jobs:
           restore-keys: ${{ env.cache-name }}
 
       - name: Setup Theos
-        if: ${{ steps.theos.outputs.cache-hit != 'true' }}
+        if: ${{ (inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc) && steps.theos.outputs.cache-hit != 'true' }}
         uses: actions/checkout@v6
         with:
           repository: theos/theos
@@ -67,7 +78,7 @@ jobs:
           submodules: recursive
 
       - name: Download iOS SDK
-        if: ${{ steps.theos.outputs.cache-hit != 'true' }}
+        if: ${{ (inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc) && steps.theos.outputs.cache-hit != 'true' }}
         run: |
           git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
           cd sdks
@@ -75,12 +86,24 @@ jobs:
           git checkout
           mv *.sdk $THEOS/sdks
 
-      - name: Checkout YTLite source
-        uses: actions/checkout@v6
-        with:
-          path: YTLite
+      - name: Download YouTube Plus (by version)
+        if: ${{ inputs.tweak_version != '' }}
+        run: |
+          deb_url="https://github.com/dayanch96/YTLite/releases/download/v${{ inputs.tweak_version }}/com.dvntm.ytlite_${{ inputs.tweak_version }}_iphoneos-arm.deb"
+          wget "$deb_url" --no-verbose -O ytplus.deb
+
+      - name: Download YouTube Plus (by URL)
+        if: ${{ inputs.tweak_url != '' }}
+        run: |
+          wget "${{ inputs.tweak_url }}" --no-verbose -O ytplus.deb
+          file_type=$(file --mime-type -b ytplus.deb)
+          if [[ "$file_type" != "application/vnd.debian.binary-package" ]]; then
+            echo "::error::Validation failed: The file is not a valid DEB file. Detected type: $file_type."
+            exit 1
+          fi
 
       - name: Clone YouTubeHeader
+        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc }}
         run: |
           if [ -d "$THEOS/include/YouTubeHeader" ]; then
             cd $THEOS/include/YouTubeHeader && git pull
@@ -91,23 +114,6 @@ jobs:
             rm -rf "$THEOS/include/YTHeaders"
             cp -r "$THEOS/include/YouTubeHeader" "$THEOS/include/YTHeaders"
           fi
-
-      # Symlink YouTubeHeader next to YTLite checkout (for ../YouTubeHeader imports)
-      - name: Symlink YouTubeHeader
-        run: ln -sf $THEOS/include/YouTubeHeader ${{ github.workspace }}/YouTubeHeader
-
-      - name: Clone protobuf headers
-        run: |
-          cd ${{ github.workspace }}
-          git clone --quiet -n --depth=1 --filter=tree:0 -b v3.21.12 https://github.com/protocolbuffers/protobuf.git protobuf
-          cd protobuf
-          git sparse-checkout set --no-cone objectivec
-          git checkout
-
-      - name: Build YouTube Afterglow from source
-        run: |
-          cd YTLite && make clean package DEBUG=0 FINALPACKAGE=1
-          mv packages/*.deb ../ytplus.deb
 
       - name: Clone PSHeader
         if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc }}
@@ -135,7 +141,8 @@ jobs:
         run: git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig.git
 
       - name: Clone YouGroupSettings
-        run: git clone --quiet --depth=1 https://github.com/xuninc/YouGroupSettings.git
+        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_demc }}
+        run: git clone --quiet --depth=1 https://github.com/PoomSmart/YouGroupSettings.git
 
       - name: Clone YouQuality
         if: ${{ inputs.enable_yq }}
@@ -148,9 +155,6 @@ jobs:
       - name: Clone DontEatMyContent
         if: ${{ inputs.enable_demc }}
         run: git clone --quiet --depth=1 https://github.com/therealFoxster/DontEatMyContent.git
-
-      - name: Clone YTIcons
-        run: git clone --quiet --depth=1 https://github.com/xuninc/YTIcons.git
 
       - name: Build YouPiP
         if: ${{ inputs.enable_youpip }}
@@ -177,6 +181,7 @@ jobs:
           mv packages/*.deb ../ytabc.deb
 
       - name: Build YouGroupSettings
+        if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_demc }}
         run: |
           cd YouGroupSettings && make clean package DEBUG=0 FINALPACKAGE=1
           mv packages/*.deb ../ygs.deb
@@ -198,11 +203,6 @@ jobs:
         run: |
           cd DontEatMyContent && make clean package DEBUG=0 FINALPACKAGE=1
           mv packages/*.deb ../demc.deb
-
-      - name: Build YTIcons
-        run: |
-          cd YTIcons && make clean package DEBUG=0 FINALPACKAGE=1
-          mv packages/*.deb ../yticons.deb
 
       - name: Clone Open in YouTube (Safari extension)
         run: |
